### ISSUE TITLE
HelloAR Unity sample app crashing

### ISSUE THREAD

**Issue by brianm-sra** [google-ar/arcore-unity-extensions#16]
I followed the instructions on the ARCore Unity "Quickstart for Android" document at
https://developers.google.com/ar/develop/unity/quickstart-android

using Unity 2019.4.3f1 Personal on Windows 10

I got it to build and install on my Samsung Galaxy S20+ 5G running Android 10

It crashes at runtime. The logcat shows the following

Error Unity AndroidJavaException: java.lang.ClassNotFoundException: com.unity3d.plugin.UnityAndroidPermissions$IPermissionRequestResult
Error Unity java.lang.ClassNotFoundException: com.unity3d.plugin.UnityAndroidPermissions$IPermissionRequestResult
Error Unity 	at java.lang.Class.classForName(Native Method)
Error Unity 	at java.lang.Class.forName(Class.java:454)
Error Unity 	at com.unity3d.player.UnityPlayer.nativeRender(Native Method)
Error Unity 	at com.unity3d.player.UnityPlayer.access$300(Unknown Source:0)
Error Unity 	at com.unity3d.player.UnityPlayer$e$1.handleMessage(Unknown Source:95)
Error Unity 	at android.os.Handler.dispatchMessage(Handler.java:103)
Error Unity 	at android.os.Looper.loop(Looper.java:237)
Error Unity 	at com.unity3d.player.UnityPlayer$e.run(Unknown Source:20)
Error Unity Caused by: java.lang.ClassNotFoundException: com.unity3d.plugin.UnityAndroidPermissions$IPermissionRequestResult
Error Unity 	... 8 more
Error Unity   at UnityEngine.AndroidJNISafe.CheckException () [0x00096] in <3c22a197ab60454cb70124c69f2248be>:0 
Error Unity   at UnityEngine.AndroidJNISafe.FindClass (System.String name) [0x0000c] in <3c22a197ab60454cb70124c69f2248be>:0 
Error Unity   at 

followed by a couple of native stack traces that mention UnityEngine.XR.Tango.TangoInputTracking:TryGetPoseAtTime

Any idea what could cause this?

**Comment by brianm-sra** [comment]
I went back to an older version of Unity, 2018.422f1 Personal, and was able to get the HelloAR scene to work now (see screenshot image below)

So maybe there is some compatibility issue with Unity 2019 seen in my original bug report from a few days ago

![Screenshot_20200713-144312_ARCore Unity Demo](https://user-images.githubusercontent.com/15881915/87356786-8c7ad000-c517-11ea-9f31-f79937c414ca.jpg)

**Comment by rsfuller** [comment]
Thanks for the report!

**We are looking into this issue currently**.

You've linked the ARCore SDK Quickstart, but you've posted in the ARCore Extensions for AR Foundation repo (see [Unity overview](https://developers.google.com/ar/develop/unity) for more info on the differences. It would be helpful to understand the Unity setup (and which version of the packages) you are using. 

Having said that, some users are experiencing a similar crash with the ARCore Extensions plugin. See the [Unity forum](https://forum.unity.com/threads/android-crash-on-local-build-asking-camera-permission-with-arcore-xr-plugin-preview-24.660466/) for context.

In the meantime (if you are using the ARCore Extensions plugin) I would suggest using one of the workarounds posted in that forum, such as turning off all Minify settings in Project Settings -> Player -> Publisher Settings (and ensure you are meeting the [minimum requirements](https://developers.google.com/ar/develop/unity-arf/quickstart-android#requirements)!).

**Comment by brianm-sra** [comment]
I've actually put my Unity work on the back burner for now and am working with Java and C++ at this time.

I think at the time that I reported this issue on July 10
I was using arcore-unity-sdk-1.18.0.unitypackage
GoogleARCore in Assets part of Project

**Comment by brianm-sra** [comment]
I think I was probably using ARCore SDK and posted the crash report in the wrong place. Sorry for the confusion.

If / when I run into issues with ARCore Extensions for AR Foundation, I will report separately with more details.
